check-for-updates: true
shooting-stars-enabled: true
falling-stars-enabled: true
begin-spawning-stars-time: 13000
end-spawning-stars-time: 23000
shooting-stars-per-minute: 8
shooting-stars-min-height: 130
shooting-stars-max-height: 160
falling-stars-per-minute: 0.01
falling-stars-radius: 75
falling-stars-sound-enabled: true
falling-stars-volume: 6
falling-stars-spark-time: 200
falling-stars-experience: 100
falling-stars-loot:
  shulker_shell: 3 
  heart_of_the_sea: 10
  diamond: 55
  disc_fragment: 10
  echo_shard: 20
  end_crystal: 2
new-moon-meteor-shower: true
shooting-stars-per-minute-during-meteor-showers: 15
falling-stars-per-minute-during-meteor-showers: 0.1
shooting-stars-summon-text: "Make a wish!"
falling-stars-summon-text: "Make a wish!"
debug: false
